spring:
  application:
    name: lynq-backend-app
  autoconfigure:
    exclude:
      - org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/lynq_backend_db
    username: root
    password: federico
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  jpa:
    open-in-view: false
    properties:
      hibernate:
        proc:
          param_null_passing: true
        ddl-auto: none
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
  liquibase:
    change-log: classpath:changelog/db.changelog-config.xml


lynq:
  iam:
    url: http://localhost:8080/lynq-iam
  aws:
    region: ${AWS_REGION:us-east-1}
    access-key-id: ${AWS_ACCESS_KEY_ID:}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
    bucket-name: ${AWS_BUCKET_NAME:}


server:
  port: 8082
  servlet:
    context-path: '/lynq-backend-app'

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  server:
    port: 8083
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ health, prometheus ]
      base-path: /actuator

logging:
  config: classpath:log4j2-spring.xml
  level:
    root: INFO
    com:
      lynq:
        backend: INFO

